AWSTemplateFormatVersion: 2010-09-09
Description: Create resources for FleetHub lab.
# aws cloudformation deploy --template-file template.yaml --stack-name iot-fleethub-lab

Resources:
  IoTJobsBucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket for IoT jobs
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref IoTJobsBucket
      PolicyDocument:
        Statement:
          - Action: 's3:*'
            Effect: Deny
            Resource:
              - !Sub 
                - 'arn:aws:s3:::${S3BucketName}'
                - S3BucketName: !Ref IoTJobsBucket
              - !Sub 
                - 'arn:aws:s3:::${S3BucketName}/*'
                - S3BucketName: !Ref IoTJobsBucket
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
            Principal: '*'

Outputs:
  IoTJobsBucket:
    Description: S3 bucket for IoT jobs
    Value: !Ref IoTJobsBucket
